# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Users/amcmahon/OneDrive - Brookhaven National Laboratory/BNL/TEST/UAS/Software/MoDaCS/instruments/gremsy_gimbal/ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(291, 238)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.pitch = QtWidgets.QLineEdit(self.groupBox_2)
        self.pitch.setObjectName("pitch")
        self.gridLayout_2.addWidget(self.pitch, 1, 0, 1, 1)
        self.roll = QtWidgets.QLineEdit(self.groupBox_2)
        self.roll.setObjectName("roll")
        self.gridLayout_2.addWidget(self.roll, 1, 1, 1, 1)
        self.yaw = QtWidgets.QLineEdit(self.groupBox_2)
        self.yaw.setObjectName("yaw")
        self.gridLayout_2.addWidget(self.yaw, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_off = QtWidgets.QPushButton(self.groupBox)
        self.pb_off.setObjectName("pb_off")
        self.gridLayout.addWidget(self.pb_off, 0, 0, 1, 1)
        self.pb_up = QtWidgets.QPushButton(self.groupBox)
        self.pb_up.setObjectName("pb_up")
        self.gridLayout.addWidget(self.pb_up, 0, 1, 1, 1)
        self.pb_mon = QtWidgets.QPushButton(self.groupBox)
        self.pb_mon.setObjectName("pb_mon")
        self.gridLayout.addWidget(self.pb_mon, 1, 0, 1, 1)
        self.pb_down = QtWidgets.QPushButton(self.groupBox)
        self.pb_down.setObjectName("pb_down")
        self.gridLayout.addWidget(self.pb_down, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Attitude (degrees)"))
        self.label.setText(_translate("Form", "Pitch:"))
        self.label_2.setText(_translate("Form", "Roll:"))
        self.label_3.setText(_translate("Form", "Yaw:"))
        self.groupBox.setTitle(_translate("Form", "Control"))
        self.pb_off.setText(_translate("Form", "Motors Off"))
        self.pb_up.setText(_translate("Form", "Pitch Up"))
        self.pb_mon.setText(_translate("Form", "Motors On"))
        self.pb_down.setText(_translate("Form", "Pitch Down"))
