# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(291, 121)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(291, 121))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(291, 40))
        self.widget.setObjectName("widget")
        self.cb_correctNonlin = QtWidgets.QCheckBox(self.widget)
        self.cb_correctNonlin.setGeometry(QtCore.QRect(170, 0, 121, 17))
        self.cb_correctNonlin.setChecked(True)
        self.cb_correctNonlin.setObjectName("cb_correctNonlin")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 5, 61, 31))
        self.label.setObjectName("label")
        self.sb_intTime = QtWidgets.QSpinBox(self.widget)
        self.sb_intTime.setGeometry(QtCore.QRect(70, 15, 71, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_intTime.sizePolicy().hasHeightForWidth())
        self.sb_intTime.setSizePolicy(sizePolicy)
        self.sb_intTime.setMinimum(1000)
        self.sb_intTime.setMaximum(65000000)
        self.sb_intTime.setSingleStep(1000)
        self.sb_intTime.setProperty("value", 10000)
        self.sb_intTime.setObjectName("sb_intTime")
        self.pb_DarkCurrent = QtWidgets.QPushButton(self.widget)
        self.pb_DarkCurrent.setGeometry(QtCore.QRect(170, 20, 91, 21))
        self.pb_DarkCurrent.setObjectName("pb_DarkCurrent")
        self.verticalLayout.addWidget(self.widget)
        self.pltWidgetframe = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pltWidgetframe.sizePolicy().hasHeightForWidth())
        self.pltWidgetframe.setSizePolicy(sizePolicy)
        self.pltWidgetframe.setMinimumSize(QtCore.QSize(291, 81))
        self.pltWidgetframe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pltWidgetframe.setObjectName("pltWidgetframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pltWidgetframe)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pltWidget = QtWidgets.QWidget(self.pltWidgetframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pltWidget.sizePolicy().hasHeightForWidth())
        self.pltWidget.setSizePolicy(sizePolicy)
        self.pltWidget.setMinimumSize(QtCore.QSize(220, 81))
        self.pltWidget.setObjectName("pltWidget")
        self.horizontalLayout.addWidget(self.pltWidget)
        self.frame = QtWidgets.QFrame(self.pltWidgetframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(71, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 71, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.pb_aqRef = QtWidgets.QPushButton(self.groupBox)
        self.pb_aqRef.setGeometry(QtCore.QRect(10, 30, 51, 23))
        self.pb_aqRef.setObjectName("pb_aqRef")
        self.pb_remlast = QtWidgets.QPushButton(self.groupBox)
        self.pb_remlast.setGeometry(QtCore.QRect(10, 50, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pb_remlast.setFont(font)
        self.pb_remlast.setObjectName("pb_remlast")
        self.lbl_count = QtWidgets.QLabel(self.groupBox)
        self.lbl_count.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.lbl_count.setObjectName("lbl_count")
        self.lbl_refcount = QtWidgets.QLabel(self.groupBox)
        self.lbl_refcount.setGeometry(QtCore.QRect(45, 10, 21, 16))
        self.lbl_refcount.setObjectName("lbl_refcount")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.pltWidgetframe)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cb_correctNonlin.setText(_translate("Form", "Correct Nonlinearity"))
        self.label.setText(_translate("Form", "Integration\n"
"Time (uS):"))
        self.pb_DarkCurrent.setText(_translate("Form", "Set Dark Current"))
        self.groupBox.setTitle(_translate("Form", "References"))
        self.pb_aqRef.setText(_translate("Form", "Acquire"))
        self.pb_remlast.setText(_translate("Form", "Rem last"))
        self.lbl_count.setText(_translate("Form", "Count:"))
        self.lbl_refcount.setText(_translate("Form", "0"))

