# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Qt/ui_large.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1080, 808)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mdiArea = QtWidgets.QMdiArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMinimumSize(QtCore.QSize(300, 300))
        self.mdiArea.setMaximumSize(QtCore.QSize(1920, 1080))
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout_3.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dw_MasterLog = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dw_MasterLog.sizePolicy().hasHeightForWidth())
        self.dw_MasterLog.setSizePolicy(sizePolicy)
        self.dw_MasterLog.setMinimumSize(QtCore.QSize(719, 181))
        self.dw_MasterLog.setFloating(False)
        self.dw_MasterLog.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dw_MasterLog.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dw_MasterLog.setObjectName("dw_MasterLog")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(701, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.plainTextEdit.setPalette(palette)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setDocumentTitle("")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.dw_MasterLog.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dw_MasterLog)
        self.dw_Conns = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dw_Conns.sizePolicy().hasHeightForWidth())
        self.dw_Conns.setSizePolicy(sizePolicy)
        self.dw_Conns.setMinimumSize(QtCore.QSize(150, 315))
        self.dw_Conns.setBaseSize(QtCore.QSize(0, 0))
        self.dw_Conns.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dw_Conns.setObjectName("dw_Conns")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(100, 150))
        self.treeWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setWordWrap(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setDefaultSectionSize(50)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(50)
        self.treeWidget.header().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.dw_Conns.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dw_Conns)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_3.sizePolicy().hasHeightForWidth())
        self.dockWidget_3.setSizePolicy(sizePolicy)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(920, 211))
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.TopDockWidgetArea)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(721, 171))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(11, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(180, 180))
        self.widget.setObjectName("widget")
        self.lcdTime = QtWidgets.QLCDNumber(self.widget)
        self.lcdTime.setGeometry(QtCore.QRect(0, 0, 91, 31))
        self.lcdTime.setSmallDecimalPoint(False)
        self.lcdTime.setDigitCount(8)
        self.lcdTime.setProperty("value", 0.0)
        self.lcdTime.setProperty("intValue", 0)
        self.lcdTime.setObjectName("lcdTime")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(100, 0, 71, 81))
        self.groupBox.setObjectName("groupBox")
        self.btn_Start_In = QtWidgets.QPushButton(self.groupBox)
        self.btn_Start_In.setGeometry(QtCore.QRect(10, 15, 51, 23))
        self.btn_Start_In.setAutoFillBackground(False)
        self.btn_Start_In.setStyleSheet("QProgressBar::chunk {background-color: #3add36; width: 1px;}")
        self.btn_Start_In.setObjectName("btn_Start_In")
        self.btn_ManTrig_In = QtWidgets.QPushButton(self.groupBox)
        self.btn_ManTrig_In.setGeometry(QtCore.QRect(10, 55, 51, 23))
        self.btn_ManTrig_In.setAutoFillBackground(False)
        self.btn_ManTrig_In.setStyleSheet("QProgressBar::chunk {background-color: #3add36; width: 1px;}")
        self.btn_ManTrig_In.setObjectName("btn_ManTrig_In")
        self.btn_Stop_In = QtWidgets.QPushButton(self.groupBox)
        self.btn_Stop_In.setGeometry(QtCore.QRect(10, 35, 51, 23))
        self.btn_Stop_In.setAutoFillBackground(False)
        self.btn_Stop_In.setStyleSheet("QProgressBar::chunk {background-color: #3add36; width: 1px;}")
        self.btn_Stop_In.setObjectName("btn_Stop_In")
        self.btn_InstRst = QtWidgets.QPushButton(self.widget)
        self.btn_InstRst.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.btn_InstRst.setAutoFillBackground(False)
        self.btn_InstRst.setStyleSheet("QProgressBar::chunk {background-color: #3add36; width: 1px;}")
        self.btn_InstRst.setObjectName("btn_InstRst")
        self.btn_ManTrig = QtWidgets.QPushButton(self.widget)
        self.btn_ManTrig.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.btn_ManTrig.setObjectName("btn_ManTrig")
        self.gb_Network = QtWidgets.QGroupBox(self.widget)
        self.gb_Network.setGeometry(QtCore.QRect(0, 90, 160, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Network.sizePolicy().hasHeightForWidth())
        self.gb_Network.setSizePolicy(sizePolicy)
        self.gb_Network.setObjectName("gb_Network")
        self.lbl_S_IP = QtWidgets.QLabel(self.gb_Network)
        self.lbl_S_IP.setGeometry(QtCore.QRect(27, 29, 121, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_S_IP.sizePolicy().hasHeightForWidth())
        self.lbl_S_IP.setSizePolicy(sizePolicy)
        self.lbl_S_IP.setMinimumSize(QtCore.QSize(120, 10))
        self.lbl_S_IP.setText("")
        self.lbl_S_IP.setScaledContents(False)
        self.lbl_S_IP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_S_IP.setObjectName("lbl_S_IP")
        self.lbl_R_IP = QtWidgets.QLabel(self.gb_Network)
        self.lbl_R_IP.setGeometry(QtCore.QRect(27, 57, 121, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_R_IP.sizePolicy().hasHeightForWidth())
        self.lbl_R_IP.setSizePolicy(sizePolicy)
        self.lbl_R_IP.setMinimumSize(QtCore.QSize(120, 10))
        self.lbl_R_IP.setText("")
        self.lbl_R_IP.setScaledContents(False)
        self.lbl_R_IP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_R_IP.setObjectName("lbl_R_IP")
        self.label_2 = QtWidgets.QLabel(self.gb_Network)
        self.label_2.setGeometry(QtCore.QRect(11, 43, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(11, 10))
        self.label_2.setObjectName("label_2")
        self.lbl_Rcount = QtWidgets.QLabel(self.gb_Network)
        self.lbl_Rcount.setGeometry(QtCore.QRect(27, 43, 120, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Rcount.sizePolicy().hasHeightForWidth())
        self.lbl_Rcount.setSizePolicy(sizePolicy)
        self.lbl_Rcount.setMinimumSize(QtCore.QSize(120, 10))
        self.lbl_Rcount.setScaledContents(False)
        self.lbl_Rcount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Rcount.setObjectName("lbl_Rcount")
        self.label = QtWidgets.QLabel(self.gb_Network)
        self.label.setGeometry(QtCore.QRect(11, 15, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.lbl_Scount = QtWidgets.QLabel(self.gb_Network)
        self.lbl_Scount.setGeometry(QtCore.QRect(27, 15, 120, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Scount.sizePolicy().hasHeightForWidth())
        self.lbl_Scount.setSizePolicy(sizePolicy)
        self.lbl_Scount.setMinimumSize(QtCore.QSize(120, 0))
        self.lbl_Scount.setScaledContents(False)
        self.lbl_Scount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Scount.setObjectName("lbl_Scount")
        self.horizontalLayout_3.addWidget(self.widget)
        self.tbl_Instruments = QtWidgets.QTableWidget(self.widget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.tbl_Instruments.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tbl_Instruments.setFont(font)
        self.tbl_Instruments.setToolTip("")
        self.tbl_Instruments.setAutoFillBackground(False)
        self.tbl_Instruments.setStyleSheet("QProgressBar::chunk {background-color: #3add36; width: 1px;}\n"
"section::{font: 12px;}")
        self.tbl_Instruments.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbl_Instruments.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_Instruments.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_Instruments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_Instruments.setAlternatingRowColors(True)
        self.tbl_Instruments.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_Instruments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_Instruments.setRowCount(0)
        self.tbl_Instruments.setColumnCount(4)
        self.tbl_Instruments.setObjectName("tbl_Instruments")
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Instruments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Instruments.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Instruments.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Instruments.setHorizontalHeaderItem(3, item)
        self.tbl_Instruments.horizontalHeader().setDefaultSectionSize(72)
        self.tbl_Instruments.horizontalHeader().setMinimumSectionSize(18)
        self.tbl_Instruments.verticalHeader().setVisible(False)
        self.tbl_Instruments.verticalHeader().setDefaultSectionSize(25)
        self.tbl_Instruments.verticalHeader().setHighlightSections(False)
        self.tbl_Instruments.verticalHeader().setSortIndicatorShown(False)
        self.tbl_Instruments.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.tbl_Instruments)
        self.horizontalLayout.addWidget(self.widget_2)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_3)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuArrange_Instrument_UIs = QtWidgets.QMenu(self.menuView)
        self.menuArrange_Instrument_UIs.setObjectName("menuArrange_Instrument_UIs")
        MainWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConenctions_Events = QtWidgets.QAction(MainWindow)
        self.actionConenctions_Events.setCheckable(True)
        self.actionConenctions_Events.setChecked(True)
        self.actionConenctions_Events.setObjectName("actionConenctions_Events")
        self.actionMaster_Log = QtWidgets.QAction(MainWindow)
        self.actionMaster_Log.setCheckable(True)
        self.actionMaster_Log.setChecked(True)
        self.actionMaster_Log.setObjectName("actionMaster_Log")
        self.actionTabbed_Mode = QtWidgets.QAction(MainWindow)
        self.actionTabbed_Mode.setCheckable(True)
        self.actionTabbed_Mode.setChecked(True)
        self.actionTabbed_Mode.setObjectName("actionTabbed_Mode")
        self.actionTile_Horizontally = QtWidgets.QAction(MainWindow)
        self.actionTile_Horizontally.setObjectName("actionTile_Horizontally")
        self.actionGitHub_Page = QtWidgets.QAction(MainWindow)
        self.actionGitHub_Page.setObjectName("actionGitHub_Page")
        self.actionTile_Cascade = QtWidgets.QAction(MainWindow)
        self.actionTile_Cascade.setObjectName("actionTile_Cascade")
        self.menuFile.addAction(self.actionQuit)
        self.menuArrange_Instrument_UIs.addAction(self.actionTabbed_Mode)
        self.menuArrange_Instrument_UIs.addSeparator()
        self.menuArrange_Instrument_UIs.addAction(self.actionTile_Horizontally)
        self.menuArrange_Instrument_UIs.addAction(self.actionTile_Cascade)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuArrange_Instrument_UIs.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dw_MasterLog.setWindowTitle(_translate("MainWindow", "Master Log"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Status Info..."))
        self.dw_Conns.setWindowTitle(_translate("MainWindow", "Connections & Events"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Signal"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Last Value"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Global Trigger"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Direct Connections"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Events"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "Instrument Control"))
        self.groupBox.setTitle(_translate("MainWindow", "Inst. Trig."))
        self.btn_Start_In.setText(_translate("MainWindow", "Start"))
        self.btn_ManTrig_In.setText(_translate("MainWindow", "Manual"))
        self.btn_Stop_In.setText(_translate("MainWindow", "Stop"))
        self.btn_InstRst.setText(_translate("MainWindow", "Reset Inst."))
        self.btn_ManTrig.setText(_translate("MainWindow", "Global Trig."))
        self.gb_Network.setTitle(_translate("MainWindow", "Network"))
        self.label_2.setText(_translate("MainWindow", "R:"))
        self.lbl_Rcount.setText(_translate("MainWindow", "--"))
        self.label.setText(_translate("MainWindow", "S:"))
        self.lbl_Scount.setText(_translate("MainWindow", "--"))
        item = self.tbl_Instruments.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Instrument"))
        item = self.tbl_Instruments.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Acq#"))
        item = self.tbl_Instruments.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tbl_Instruments.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data Path"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuArrange_Instrument_UIs.setTitle(_translate("MainWindow", "Arrange Instrument UIs"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionConenctions_Events.setText(_translate("MainWindow", "Connections and Events"))
        self.actionMaster_Log.setText(_translate("MainWindow", "Master Log"))
        self.actionTabbed_Mode.setText(_translate("MainWindow", "Tabbed Mode"))
        self.actionTile_Horizontally.setText(_translate("MainWindow", "Tile Horizontally"))
        self.actionGitHub_Page.setText(_translate("MainWindow", "GitHub Page"))
        self.actionTile_Cascade.setText(_translate("MainWindow", "Cascade"))

